name = "Calphad"
uuid = "6ed6615d-e536-488c-bf7e-838fb4a03eb1"
authors = ["Brandon Bocklund"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
